### ISSUE TITLE
Error in "Plot the Analysis Results" Module with limited shoreline data

### ISSUE THREAD

**Issue by ArnauGT98** [AlbertGallegoJimenez/SEATool#5]
## Description
I have detected an issue in the "Plot the Analysis Results" module of our tool. This problem occurs when performing a coastline evolution analysis (calculating retreat rates per year for each transect) with a minimal number of shorelines.

## Error Traceback
Traceback (most recent call last):
  File "C:\Users\...\...\...\...TOOLBOXES\shoreline-evolution-toolbox\src\tools\plotResults.py", line 83, in execute
    plotter.plot_seasonality(transects2plot=transectsID_2plot)
  File "C:\Users\...\...\...\...TOOLBOXES\shoreline-evolution-toolbox\src\tools\utils\plot_results.py", line 270, in plot_seasonality
    shore_month = shore_month.append({'month': m,
  File "C:\Users\...\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'

## Question
How this issue can be solved?
How do you recomend to proceed?

**Comment by AlbertGallegoJimenez** [comment]
Currently fixed in version v1.3.2.
